# Generated by Django 3.2.25 on 2025-05-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(max_length=10)),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('bedrooms', models.IntegerField(null=True)),
                ('home_size', models.IntegerField(null=True)),
                ('home_type', models.CharField(max_length=50)),
                ('last_sold_date', models.DateField(null=True)),
                ('last_sold_price', models.IntegerField(null=True)),
                ('link', models.URLField(max_length=500)),
                ('price', models.BigIntegerField(null=True)),
                ('property_size', models.IntegerField(null=True)),
                ('rent_price', models.IntegerField(null=True)),
                ('rentzestimate_amount', models.IntegerField(null=True)),
                ('rentzestimate_last_updated', models.DateField(null=True)),
                ('tax_value', models.IntegerField(null=True)),
                ('tax_year', models.IntegerField(null=True)),
                ('year_built', models.IntegerField(null=True)),
                ('zestimate_amount', models.IntegerField(null=True)),
                ('zestimate_last_updated', models.DateField(null=True)),
                ('zillow_id', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_imported_at', models.DateTimeField(null=True)),
                ('data_hash', models.CharField(max_length=64, null=True)),
            ],
            options={
                'ordering': ['-zestimate_amount'],
            },
        ),
    ]
